language: php

php:
  - '7.1.0'
  - '7.1.16'
  - '7.2.0'
  - '7.2.1'
  - '7.2.2'
  - '7.2.3'
  - '7.2.4'
  - nightly

install:
  - composer install

script:
  - php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_script:
  - php vendor/bin/codacycoverage clover build/coverage/xml